project_structure = [
    # api
    {item_path = "{{ context.project }}.api", item_file = "pom.xml", item_tmpl = "api-pom.xml.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.api.src.main.java.{{context.group}}.{{context.project}}.api", item_file = "HelloController.java", item_tmpl = "HelloController.java.tmpl", item_type = "static"},

    # app
    {item_path = "{{ context.project }}.app", item_file = "pom.xml", item_tmpl = "app-pom.xml.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.app.src.main.java.{{context.group}}.{{context.project}}.biz", item_file = "HelloControllerImpl.java", item_tmpl = "HelloControllerImpl.java.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.app.src.main.java.{{context.group}}.{{context.project}}.fun", item_file = "ExceptionUtil.java", item_tmpl = "ExceptionUtil.java.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.app.src.main.java.{{context.group}}.{{context.project}}.fun", item_file = "ExecuteContext.java", item_tmpl = "ExecuteContext.java.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.app.src.main.java.{{context.group}}.{{context.project}}.fun", item_file = "FuncResult.java", item_tmpl = "FuncResult.java.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.app.src.main.java.{{context.group}}.{{context.project}}.fun", item_file = "Log.java", item_tmpl = "Log.java.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.app.src.main.java.{{context.group}}.{{context.project}}.fun", item_file = "LogAspect.java", item_tmpl = "LogAspect.java.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.app.src.main.java.{{context.group}}.{{context.project}}.fun", item_file = "StringUtil.java", item_tmpl = "StringUtil.java.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.app.src.main.java.{{context.group}}.{{context.project}}.fun", item_file = "JsonUtil.java", item_tmpl = "JsonUtil.java.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.app.src.main.java.{{context.group}}.{{context.project}}", item_file = "Application.java", item_tmpl = "Application.java.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.app.src.main.resources.db.migration", item_file = "V1__create_entity_basic_info.sql", item_tmpl = "V1__create_entity_basic_info.sql.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.app.src.main.resources", item_file = "application.yaml", item_tmpl = "application.yaml.tmpl", item_type = "static"},

    {item_path = "{{ context.project }}.app.src.test.java.{{context.group}}.{{context.project}}.biz", item_file = "HelloControllerSpec.groovy", item_tmpl = "HelloControllerSpec.groovy.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.app.src.test.java.{{context.group}}.{{context.project}}.dal", item_file = "EntityBasicInfoDaoSpec.groovy", item_tmpl = "EntityBasicInfoDaoSpec.groovy.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.app.src.test.resources.db.migration", item_file = "V1__create_entity_basic_info.sql", item_tmpl = "test-V1__create_entity_basic_info.sql.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}.app.src.test.resources", item_file = "application.yaml", item_tmpl = "test-application.yaml.tmpl", item_type = "static"},


    # gen
    {item_path = "{{ context.project }}.gen", item_file = "pom.xml", item_tmpl = "gen-pom.xml.tmpl", item_type = "static"},


    # root
    {item_path = "{{ context.project }}", item_file = "pom.xml", item_tmpl = "pom.xml.tmpl", item_type = "static"},
    {item_path = "{{ context.project }}", item_file = "run.sh", item_tmpl = "run.sh.tmpl", item_type = "static"}
]